run:
  deadline: 5m
  allow-parallel-runners: true

linters:
  enable:
    - dupl
    - errcheck
    - exportloopref
    - gocyclo
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unparam
    - unused
    - lll

linters-settings:
  lll:
    line-length: 120
