timeout: 30
triggers:
  - name: create-release
    type: git_poller
    params:
      GIT_URL: "https://github.com/doanac/fioctl.git"
      GIT_POLL_REFS: "refs/tags/*"
    runs:
      - name: create-binaries
        container: golang:1.19.0
        host-tag: amd64
        script: create-binaries

scripts:

  unit-test: |
    #!/bin/sh -ex
    make check
