name: Test Build

on:
  push:
  pull_request:

jobs:
  build-binaries:
    name: Build ${{ matrix.binary }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: fioctl-linux-amd64
          - os: ubuntu-latest
            binary: fioctl-linux-arm64
            qemu: true
            qemu-platform: arm64
          # Let's build on the ubuntu to be faster
          - os: ubuntu-latest
            binary: fioctl-windows-amd64.exe
          - os: macos-latest
            binary: fioctl-darwin-amd64
          - os: ubuntu-latest
            binary: fioctl-linux-armv7
            qemu: true
            qemu-platform: armv7
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: matrix.qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.qemu-platform }}

      - name: Build Binary
        run: |
          if [ "${{ matrix.binary }}" == "fioctl-windows-amd64.exe" ]; then
            make fioctl-windows-amd64
          else
            make ${{ matrix.binary }}
          fi

      - name: Archive Binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: bin/${{ matrix.binary }}

  test:
    needs: build-binaries
    name: Check ${{ matrix.binary }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: fioctl-linux-amd64
          - os: ubuntu-latest
            binary: fioctl-linux-arm64
            qemu: true
            qemu-platform: arm64
          - os: windows-latest
            binary: fioctl-windows-amd64.exe
          - os: macos-latest
            binary: fioctl-darwin-amd64
          - os: ubuntu-latest
            binary: fioctl-linux-armv7
            qemu: true
            qemu-platform: armv7
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up QEMU
        if: matrix.qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.qemu-platform }}

      - name: Download Binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: bin/

      - name: Set Execute Permission
        if: runner.os != 'Windows'
        run: chmod +x ./bin/${{ matrix.binary }}

      - name: Test Binary
        run: |
          $output = ""
          if ($env:RUNNER_OS -eq "Windows") {
            $output = .\bin\${{ matrix.binary }} targets list 2>&1
          } else {
            $output = ./bin/${{ matrix.binary }} targets list 2>&1
          }
          if ($output -notmatch "ERROR: Please run: \"fioctl login\" first") {
            throw "Unexpected output: $output"
          }
        shell: pwsh
      

