name: Test Build

on:
  push:
  pull_request:

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container
        run: |
          make container-init

      - name: Run Container to Build Binaries
        run: docker run --rm -v $(pwd):/fioctl fioctl-build make build

      - name: Copy Binaries from Container
        run: |
          container_id=$(docker create fioctl-build)
          docker cp $container_id:/fioctl/bin ./bin
          docker rm $container_id

      - name: Archive Binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/

  test:
    needs: build-binaries
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: fioctl-linux-amd64
          - os: windows-latest
            binary: fioctl-windows-amd64.exe
          - os: macos-latest
            binary: fioctl-darwin-amd64
          - os: macos-latest
            binary: fioctl-darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: bin/

      - name: Set Execute Permission
        run: chmod +x ./bin/${{ matrix.binary }}
        if: runner.os != 'Windows'

      - name: Test Binary
        run: ./bin/${{ matrix.binary }} logout
